apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      name: database
      targetPort: 9200
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      name: elasticsearch-pod
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch-container
          image: elasticsearch_img
          imagePullPolicy: Never
          ports:
            - containerPort: 9200
              name: database
