apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express
  ports:
    - port: 3002
      name: server
      targetPort: 3002
      # nodePort: 30002
    - port: 3001
      name: swagger
      targetPort: 3001
      # nodePort: 30001
  type: LoadBalancer
  # type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      name: express-pod
      labels:
        app: express
    spec:
      containers:
        - name: express-container
          image: express_img
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
              name: server
            - containerPort: 3001
              name: swagger
