apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      name: kibana
      targetPort: 5601
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      name: kibana-pod
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana-container
          image: kibana_img
          imagePullPolicy: Never
          ports:
            - containerPort: 5601
              name: kibana
